### ISSUE TITLE
Single-key tasks not working

### ISSUE THREAD

**Issue by tonydero** [bazhenov/ttr#13]
I installed this two years ago and completely forgot about it. I was working to set it up today, and the only tasks that seem to run are the ones that are chained-key tasks like in the config provided in the readme, e.g. `ttr` -> `gg`:
```yaml
groups:
- name: git
  key: g
  tasks:
  - name: lazygit
    key: g
    cmd: lazygit
```
The config provided in the repo itself, however, has options to use single keys, e.g. `ttr` -> `d`:
```yaml
groups:
- name: date
  key: d
  cmd: date
```
This doesn't work though, and just says `No tasks configured`. I was wondering if `ttr` is intended to no longer work with the single-key tasks, or if there is a change to the syntax for single-key tasks I'm not finding in the documentation somewhere.

Thanks for this awesome tool. I much prefer this to having a ton of aliases like I did previously.

**Comment by bazhenov** [comment]
No, this is definitely a bug. I will fix it. Thank you for the feedback.

**Comment by bazhenov** [comment]
Sorry for the late reply... Indeed, `.ttr.yaml` in the project contains incorrect configuration. Tasks needs to be configured in `tasks` key, not `groups`. I've fixed that issue. Just make sure that all your configs has projects and groups separated:

```yaml
groups:
- name: git
  key: g
  tasks:
  - name: lazygit
    key: g
    cmd: lazygit
tasks:
- name: date
  key: d
  cmd: date
```
