### ISSUE TITLE
Ability to pass env vars in commands

### ISSUE THREAD

**Issue by ErikBooij** [bazhenov/ttr#17]
It appears to be impossible currently to pass environment values in commands, as `ttr` will see it as a command and will therefore try to execute it.

Example:

```
groups:
  - name: Build
    key: b
    tasks:
      - name: Frontend
        key: f
        cmd: NODE_ENV=production npm run build
```

Output:

```
sh: line 0: exec: NODE_ENV=production: not found

   Task failed (exit status: 127)

   Press Enter to continue. repeat or select another task...

```

I'm excited to make `ttr` my goto task runner, but this is currently blocking me from doing so, since I have a lot of commands that use environment variables to pass options.

Explicit passing the env as a YAML map would also be a totally fine solution by the way.
