### ISSUE TITLE
Making a command using "cd" doesn't work?

### ISSUE THREAD

**Issue by yekyam** [bazhenov/ttr#2]
Hello,

Recently, I wanted to create a .ttr.yaml shortcut to cd into frequent directories.

However, when I run the script, nothing happens?

Here's how my .ttr.yaml file looks like:

```
- name: goto-c
   key: c
   cmd: cd ~/coding/c/projects
```

I'm on MacOS.

**Comment by bazhenov** [comment]
`cd` is builtin shell command, so it can't change working directory of already running shell process. What you can do instead is spawn new shell process in directory:

```yaml
- name: goto-c
  key: c
  cmd: bash # change to shell you are using
  working_dir: /absolute/path/to/directory
```
